# Image légère + Node 20
FROM node:20-alpine

WORKDIR /app

# Améliore la vitesse d'install
ENV CI=true
ENV npm_config_loglevel=warn

# Copie des manifests d'abord (cache)
COPY package.json package-lock.json* ./

RUN npm ci || npm i

# Copie du code
COPY . .

# Pour tsx / ts-node-dev (au choix)
# npm run dev lancé par docker-compose
EXPOSE 4000
